### ISSUE TITLE
stripIndent with stripIndent'ed string inside doesn't strip some indents

### ISSUE THREAD

**Issue by hogart** [declandewet/common-tags#22]
Test case:

``` js
const stripIndent = require('common-tags').stripIndent;

const line1 = stripIndent`
    line1.0
    line1.1`;

console.log(line1);

const line2 = stripIndent`
    ${line1}
    line2.0`;

console.log(line2);
```

Output: 

```
line1.0
line1.1
line1.0
line1.1
    line2.0
```

As you see, `line2.0` isn't de-indented. I'm not sure if it's expected behaviour. If so, how can I achieve desired effect? Thanks for nice lib!

**Comment by declandewet** [comment]
@hogart I haven't found a need for this as it's quite edge-case. The current algorithm only strips out the largest _leading_ indent and leaves regular indents untouched. I'll have to consult with some other algorithms and see what they do, but I do plan on adding a `stripIndents` tag which strips _all_ indentation line-per-line. This feature addition will be coming after a refactor to the way the core of this module works, which I can't get around to doing just yet because of work, but I will as soon as I have some time, promise :)

**Comment by declandewet** [comment]
I've added `stripIndemts` but will be leaving this issue open and update it with my findings when I have time to work on this project again :)

**Comment by hogart** [comment]
Wow, thanks a lot:)
