### ISSUE TITLE
Remove `null` values from `html` output

### ISSUE THREAD

**Issue by declandewet** [declandewet/common-tags#29]
Currently, the `html` tag produces invalid markup when a `null` value is encountered:

```js
import {html} from 'common-tags'

const todos = [{
  task: 'some task',
  done: false
}, {
  task: 'other task',
  done: true
}]

html`
  <h1>Incomplete tasks:</h1>
  <ul>
    ${todos.map((t) => t.done ? null : `<li>${t.task}</li>`)}
  </ul>
`
```

Produces:

```html
<h1>Incomplete tasks</h1>
<ul>
  <li>some task</li>
  null
</ul>
```

**Comment by DriesVandermeulen** [comment]
Was having a similar problem with undefined.... Maybe this functionality should be implemented as a separate tag. A tag witch removes 'undefined', 'NaN' and 'null' and replaces them with empty string values.

**Comment by declandewet** [comment]
@DriesVandermeulen when I get some time, I'll try push a fix for this over the weekend :shipit: rather swamped at the moment

**Comment by shannonmoeller** [comment]
I'd recommend replacing Boolean values as well. I often use the following pattern:

```js
export default ({ hasNext, hasPrevious }) => html`
    <fieldset>
        ${hasNext && html`
            <button x-next>Next</button>
        `}

        ${hasPrevious && html`
            <button x-prev>Previous</button>
        `}
    </fieldset>
`;
```

Where `hasNext` and `hasPrevious` are booleans, this pattern prints `false` when rendering the first and last steps because there is no next or previous. I may be the exception, but I almost never need to print a literal Boolean value.
